"use client";

import { useState } from "react";

type Cat = "Upload" | "Transform" | "Analyze" | "Manage" | "Deliver";
type Status = "live" | "designed";

interface Cap {
  cat: Cat;
  name: string;
  use: string;
  where: string;
  status: Status;
}

// "live" = implemented in this repository. It has been typechecked and built, but not yet run against a live Cloudinary account.
const CAPS: Cap[] = [
  { cat: "Upload", name: "Signed uploads", use: "The browser uploads straight to Cloudinary. The server only signs an allowlist of parameters, so the API secret never leaves it.", where: "app/api/sign-upload/route.ts", status: "live" },
  { cat: "Upload", name: "Upload preset", use: "One preset, pramaan_evidence, enforces signed mode, allowed formats and backup, and switches on the inspection options below.", where: "scripts/setup-cloudinary.ts", status: "live" },
  { cat: "Upload", name: "In-upload eval gate", use: "A JavaScript snippet runs inside Cloudinary at upload time and tags no_gps, blurry, has_faces and edited_software, and copies EXIF time, device and pHash into context.", where: "scripts/setup-cloudinary.ts", status: "live" },
  { cat: "Upload", name: "media_metadata, phash, faces, quality_analysis", use: "Raw signals the trust score is built from, produced by Cloudinary rather than re-derived by us.", where: "scripts/setup-cloudinary.ts", status: "live" },
  { cat: "Upload", name: "Upload widget", use: "Desk staff import bundles from Drive, Dropbox or local files through the same signed path.", where: "app/(dashboard)/import/page.tsx", status: "live" },
  { cat: "Transform", name: "Named transformations", use: "Seven reusable recipes (thumb, detail, analysis, public-safe, pair-half, two social crops) so a recipe is a name, not a copy-pasted string.", where: "scripts/setup-cloudinary.ts", status: "live" },
  { cat: "Transform", name: "Consent-aware redaction", use: "Delivery URLs pixelate faces unless consent is on file or not required.", where: "lib/url-builder.ts", status: "live" },
  { cat: "Transform", name: "Overlay composite", use: "Before and after placed side by side with BEFORE and AFTER labels, generated by URL alone.", where: "lib/url-builder.ts", status: "live" },
  { cat: "Transform", name: "Fill, auto gravity, f_auto, q_auto", use: "Slider images are cropped around the subject and served in the best format for each browser.", where: "lib/url-builder.ts", status: "live" },
  { cat: "Analyze", name: "AI Vision with a JSON schema", use: "Cloudinary's AI Vision reads a 1024 px derivative and answers in a fixed schema: activity, claim match, people, recapture and synthetic cues.", where: "jobs/analyze-image.ts", status: "live" },
  { cat: "Analyze", name: "Video AI (transcripts, chapters)", use: "Field videos would get the same treatment: transcribed, chaptered and scored.", where: "04_solution/05_ai_pipeline_design.md", status: "designed" },
  { cat: "Manage", name: "Webhook notifications", use: "Cloudinary calls back when an upload finishes. The signature is verified before anything runs, and a failure returns 500 so Cloudinary retries.", where: "app/api/cloudinary/webhook/route.ts", status: "live" },
  { cat: "Manage", name: "Moderation status", use: "A reviewer's decision is mirrored into Cloudinary so the DAM and the database agree.", where: "app/(dashboard)/review/actions.ts", status: "live" },
  { cat: "Manage", name: "Structured metadata + Search API", use: "activity and trust_score are written back as metadata fields; Claude plans a query, the server whitelists it, Cloudinary Search runs it.", where: "app/api/search/route.ts", status: "live" },
  { cat: "Manage", name: "Tag-based PDF packs", use: "Verified evidence is tagged and rendered into a PDF with multi() for a funder report.", where: "app/api/stories/route.ts", status: "live" },
  { cat: "Manage", name: "C2PA content credentials", use: "Signed provenance on published derivatives. Needs a beta enrolment on the account.", where: "04_solution/07_evidence_integrity_and_traceability.md", status: "designed" },
  { cat: "Deliver", name: "Versioned delivery URLs", use: "Every URL pins the asset version, so the exact bytes a funder saw can be re-fetched.", where: "lib/url-builder.ts", status: "live" },
];

const CATS: ("All" | Cat)[] = ["All", "Upload", "Transform", "Analyze", "Manage", "Deliver"];

export function CapabilityMap() {
  const [cat, setCat] = useState<"All" | Cat>("All");
  const shown = CAPS.filter((c) => cat === "All" || c.cat === cat);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap gap-2" role="tablist" aria-label="Filter by area">
        {CATS.map((c) => (
          <button
            key={c}
            role="tab"
            aria-selected={cat === c}
            onClick={() => setCat(c)}
            className={`rounded-full border px-4 py-1.5 text-sm transition ${
              cat === c ? "border-lime bg-lime font-medium text-lime-ink" : "border-line-bright text-soft hover:text-white"
            }`}
          >
            {c}
          </button>
        ))}
      </div>
      <div className="grid gap-px overflow-hidden rounded-xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-3">
        {shown.map((c) => (
          <article key={c.name} className="flex flex-col gap-3 bg-ink p-6">
            <div className="flex items-center justify-between gap-2">
              <span className="chip-cyan">{c.cat}</span>
              <span className={`chip ${c.status === "live" ? "bg-lime/15 text-lime" : "bg-white/10 text-muted"}`}>
                {c.status === "live" ? "In the code" : "Designed"}
              </span>
            </div>
            <h3 className="text-xl font-normal leading-snug">{c.name}</h3>
            <p className="flex-1 text-sm font-light leading-relaxed text-white/80">{c.use}</p>
            <p className="break-all font-mono text-[11px] text-muted">{c.where}</p>
          </article>
        ))}
      </div>
    </div>
  );
}
