-- Agentic investigation layer: activity briefs, LangGraph investigations, human-in-the-loop
-- checkpoints, and pgvector embeddings for hybrid (SQL + semantic) retrieval.
-- Embeddings are 768-dim (Gemini embedding model with outputDimensionality = 768).

create extension if not exists vector with schema extensions;
set search_path = public, extensions;

-- What the user wants to demonstrate for a site. Drives every agent's context.
create table if not exists activity_brief (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references site(id) on delete cascade,
  objective text not null,
  activity_type text not null,
  period_start date,
  period_end date,
  claims_to_establish text[] not null default '{}',
  evidence_types text[] not null default '{}',
  investigation_plan jsonb, -- generated by the planner after the brief is saved
  created_at timestamptz not null default now(),
  check (period_end is null or period_start is null or period_end >= period_start)
);
create index if not exists activity_brief_site_idx on activity_brief (site_id, created_at);

create table if not exists investigation (
  id text primary key, -- inv_<shortId>
  site_id uuid not null references site(id) on delete cascade,
  brief_id uuid references activity_brief(id) on delete set null,
  status text not null default 'running'
    check (status in ('queued','running','complete','waiting_human','error')),
  langgraph_state jsonb not null default '{}',
  progress jsonb not null default '[]', -- ordered node completions, for the UI
  error text,
  report_id text references story(id) on delete set null,
  triggered_by text not null default 'user' check (triggered_by in ('user','upload','schedule')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists investigation_site_idx on investigation (site_id, created_at);

create table if not exists hitl_checkpoint (
  id bigserial primary key,
  investigation_id text not null references investigation(id) on delete cascade,
  evidence_id text not null references evidence(id) on delete cascade,
  reason text not null,
  agent text not null,
  options jsonb not null,
  decision text,
  decision_note text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  unique (investigation_id, evidence_id)
);
create index if not exists hitl_investigation_idx on hitl_checkpoint (investigation_id);

alter table understanding add column if not exists embedding extensions.vector(768);
create index if not exists understanding_embedding_idx
  on understanding using hnsw (embedding extensions.vector_cosine_ops);

-- Hybrid retrieval: SQL filters (site, phase, trust) + pgvector cosine ranking.
create or replace function match_evidence_hybrid(
  p_query_embedding extensions.vector(768),
  p_site_id uuid,
  p_phase text default null,
  p_min_trust int default 60,
  p_limit int default 20
)
returns table (
  evidence_id text,
  caption text,
  phase text,
  trust_score int,
  trust_status text,
  similarity double precision
)
language sql stable
set search_path = public, extensions
as $$
  select
    e.id,
    u.caption,
    e.phase,
    e.trust_score,
    e.trust_status,
    1 - (u.embedding <=> p_query_embedding) as similarity
  from evidence e
  join understanding u on u.evidence_id = e.id
  where e.site_id = p_site_id
    and (p_phase is null or e.phase = p_phase)
    and e.trust_score >= p_min_trust
    and e.trust_status <> 'rejected'
    and u.embedding is not null
  order by u.embedding <=> p_query_embedding
  limit least(greatest(p_limit, 1), 100);
$$;

-- Same access model as the baseline schema: RLS on, no anon/authenticated access.
alter table activity_brief enable row level security;
alter table investigation enable row level security;
alter table hitl_checkpoint enable row level security;
revoke all on activity_brief, investigation, hitl_checkpoint from anon, authenticated;
revoke all on sequence hitl_checkpoint_id_seq from anon, authenticated;
revoke execute on function match_evidence_hybrid(extensions.vector, uuid, text, int, int) from public, anon, authenticated;
grant execute on function match_evidence_hybrid(extensions.vector, uuid, text, int, int) to service_role;
